### ISSUE TITLE
Create cityjson from 3dbag dump.

### ISSUE THREAD

**Issue by GinaSt** [cityjson/cjio_dbexport#31]
* cjio_dbexport version: 0.8.8
* Python version: 3.7.5
* Operating System: Ubuntu 19.10

### Description

I have made a dump of the 3D bag and I am trying now to create a cityjson file with the load22_3d information using the command:

`cjdb --log DEBUG ./config.yaml export_bbox 148528.0213 490644.6947 148922.1004 491072.46513 40910000.json `

However I am unsure how to connect to the tables pand & lod22_3d.

### What I Did

At the moment, every time I want a specific building or area I first join pand and lod22_3d tables and then I create a table with only the buildings of interest. My config file looks like this. Is there a better way to structure the config file to avoid joining the tables? 
```

geometries:
  lod: 2.2
  type: MultiSurface

database:
  dbname: db
  host: localhost
  port: 5432
  user: username
  password: password

tile_index:
  schema: tile_index
  table: tile_index_1
  srid: 7415
  field:
    pk: id
    geometry: geom

cityobject_type:
  Building:
    - schema: bag3d
      table: lod22_3ds_selection
      field:
        pk: fid
        geometry:
          lod22:
            name: geometrie3d
            type: Solid
        cityobject_id: identificatie
```
